# Edit the values below to customize your islet!

## Basic info ##
blogName: "reese"
authorName: "reese sapphire"
authorLink: "https://mspsocial.net/@reese" # Enter your website, social media, etc. Some way for people to tell you they like your blog! (Leaving it empty is okay too)

## Theme customization ##
# themeURL: /style/morningNews.css # Link to a theme file. Can be relative (on this server) or absolute (somewhere on the web)
backgroundImage: "" # Optional, uses theme default if left blank.

## Navigation ##
recentPostsCutoff: 4

## Behind the scenes stuff ##
serverPort: 3000
metaDescription: # This description is not directly visible on the page, but it can show up in certain places like search engines.
  "Hey, I'm reese! This is my personal website where you can find my code projects and writings."
truncateSummaryAt: 280 # Maximum length of the post summary that's used in the meta description tag for blog post pages.
language: en-US # The language you primarily write in. Not required but recommended.
blogURL: "https://reese.ovine.xyz" # The web address of this blog, used for links in the RSS feed.
